const STATIONS = [
  {key:'North',zh:'北区',en:'North',type:'general',lon:114.13,lat:22.50,district:'North District'},
  {key:'Sha Tin',zh:'沙田',en:'Sha Tin',type:'general',lon:114.18,lat:22.38,district:'Sha Tin District'},
  {key:'Tai Po',zh:'大埔',en:'Tai Po',type:'general',lon:114.16,lat:22.45,district:'Tai Po District'},
  {key:'Yuen Long',zh:'元朗',en:'Yuen Long',type:'general',lon:114.02,lat:22.45,district:'Yuen Long District'},
  {key:'Tuen Mun',zh:'屯门',en:'Tuen Mun',type:'general',lon:113.98,lat:22.39,district:'Tuen Mun District'},
  {key:'Tung Chung',zh:'东涌',en:'Tung Chung',type:'general',lon:113.94,lat:22.29,district:'Islands District'},
  {key:'Tsuen Wan',zh:'荃湾',en:'Tsuen Wan',type:'general',lon:114.11,lat:22.37,district:'Tsuen Wan District'},
  {key:'Kwai Chung',zh:'葵涌',en:'Kwai Chung',type:'general',lon:114.13,lat:22.36,district:'Kwai Tsing District'},
  {key:'Sham Shui Po',zh:'深水埗',en:'Sham Shui Po',type:'general',lon:114.16,lat:22.33,district:'Sham Shui Po District'},
  {key:'Kwun Tong',zh:'观塘',en:'Kwun Tong',type:'general',lon:114.22,lat:22.31,district:'Kwun Tong District'},
  {key:'Central/Western',zh:'中西区',en:'Central / Western',type:'general',lon:114.14,lat:22.29,district:'Central and Western District'},
  {key:'Eastern',zh:'东区',en:'Eastern',type:'general',lon:114.22,lat:22.28,district:'Eastern District'},
  {key:'Southern',zh:'南区',en:'Southern',type:'general',lon:114.16,lat:22.25,district:'Southern District'},
  {key:'Tseung Kwan O',zh:'将军澳',en:'Tseung Kwan O',type:'general',lon:114.26,lat:22.32,district:'Sai Kung District'},
  {key:'Tap Mun',zh:'塔门',en:'Tap Mun',type:'general',lon:114.36,lat:22.47,district:'Tai Po District'},
  {key:'Causeway Bay',zh:'铜锣湾',en:'Causeway Bay',type:'roadside',lon:114.184,lat:22.280,district:'Wan Chai District'},
  {key:'Central',zh:'中环',en:'Central',type:'roadside',lon:114.158,lat:22.282,district:'Central and Western District'},
  {key:'Mong Kok',zh:'旺角',en:'Mong Kok',type:'roadside',lon:114.169,lat:22.318,district:'Yau Tsim Mong District'}
];

const API = 'https://dashboard.data.gov.hk/api/aqhi-individual?format=json';
const FORECAST_API = 'https://static.data.gov.hk/opendata/dataset/aqhi/aqhi-forecast.json';
const SVG_NS = 'http://www.w3.org/2000/svg';
const state = {filter:'all',query:'',selected:'Central/Western',values:new Map(),forecast:[],dataMode:'loading',published:null,forecastMode:'loading',zoom:1,panX:0,panY:0,mapReady:false,popupOpen:false,mapMode:'current',historyReport:null,historyTime:null,historyRows:new Map()};
const el = id => document.getElementById(id);
const svgNode = (tag,attrs={}) => {const n=document.createElementNS(SVG_NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));return n};
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const typeText = type => type==='roadside'?'路边站':'一般站';
const riskText = risk => ({Low:'低',Moderate:'中',High:'高','Very High':'甚高',Serious:'严重'})[risk] || '暂无';
const riskClass = risk => ({Low:'low',Moderate:'moderate',High:'high','Very High':'very-high',Serious:'serious'})[risk] || 'unknown';
const score = v => v === '10+' ? 11 : Number(v);
const formatDate = v => {if(!v)return '暂无时间';const [date,time=''] = String(v).split('T');return `${date?.slice(5).replace('-','.') || ''} · ${time.slice(0,5)}`};
const hktTimestamp = v => {const t=Date.parse(`${v}+08:00`);return Number.isFinite(t)?t:null};
const isStale = v => {const t=hktTimestamp(v);return !t || Date.now()-t>3*60*60*1000};

function geometryCoords(g){return g.type==='Polygon'?[g.coordinates]:g.coordinates}
function allPoints(features){const pts=[];for(const f of features)for(const poly of geometryCoords(f.geometry))for(const ring of poly)for(const point of ring)pts.push(point);return pts}
function projection(features){const points=allPoints(features), minLon=Math.min(...points.map(p=>p[0])),maxLon=Math.max(...points.map(p=>p[0])),minLat=Math.min(...points.map(p=>p[1])),maxLat=Math.max(...points.map(p=>p[1]));const cos=.925,dx=(maxLon-minLon)*cos,dy=maxLat-minLat,scale=Math.min(880/dx,580/dy),left=(1000-dx*scale)/2,top=(680-dy*scale)/2;return ([lon,lat])=>[left+(lon-minLon)*cos*scale,top+(maxLat-lat)*scale]}
function layoutStationLabels(){const occupied=[];const candidates=[[16,-12,'start'],[-16,-12,'end'],[16,20,'start'],[-16,20,'end'],[0,-24,'middle'],[0,32,'middle'],[30,-7,'start'],[-30,-7,'end'],[30,26,'start'],[-30,26,'end']];const ordered=[...STATIONS].sort((a,b)=>STATIONS.filter(s=>s!==b&&Math.hypot(s.x-b.x,s.y-b.y)<65).length-STATIONS.filter(s=>s!==a&&Math.hypot(s.x-a.x,s.y-a.y)<65).length);for(const s of ordered){const label=document.querySelector(`.station-marker[data-key="${CSS.escape(s.key)}"] .station-name-label`),width=s.zh.length*12+6;let best=null;for(const [dx,dy,anchor] of candidates){const x=s.x+dx,y=s.y+dy,left=anchor==='end'?x-width:anchor==='middle'?x-width/2:x,box={left,right:left+width,top:y-12,bottom:y+2};const out=box.left<8||box.right>992||box.top<8||box.bottom>670;const overlaps=occupied.filter(other=>box.left<other.right+4&&box.right>other.left-4&&box.top<other.bottom+4&&box.bottom>other.top-4).length;const coversMarker=STATIONS.filter(other=>other!==s&&other.x>box.left-9&&other.x<box.right+9&&other.y>box.top-9&&other.y<box.bottom+9).length;const penalty=(out?100:0)+overlaps*20+coversMarker*10+Math.hypot(dx,dy)/100;if(!best||penalty<best.penalty)best={x,y,anchor,box,penalty}}label.setAttribute('x',best.x);label.setAttribute('y',best.y);label.setAttribute('text-anchor',best.anchor);occupied.push(best.box)}}
function pathForGeometry(geometry,project){const commands=[];for(const poly of geometryCoords(geometry))for(const ring of poly){ring.forEach((point,i)=>{const [x,y]=project(point);commands.push(`${i?'L':'M'}${x.toFixed(2)},${y.toFixed(2)}`)});commands.push('Z')}return commands.join(' ')}

async function loadMap(){try{const [districtResponse,landResponse]=await Promise.all([fetch('./data/districts.json'),fetch('./data/land.geojson')]);if(!districtResponse.ok||!landResponse.ok)throw new Error('无法读取地图数据');const [geo,land]=await Promise.all([districtResponse.json(),landResponse.json()]);if(!Array.isArray(geo.features)||geo.features.length!==18||!land.features?.length)throw new Error('地理数据不完整');const project=projection(geo.features);const districtLayer=el('district-layer');const landData=pathForGeometry(land.features[0].geometry,project);const mask=svgNode('clipPath',{id:'land-mask',clipPathUnits:'userSpaceOnUse'});mask.append(svgNode('path',{d:landData,'clip-rule':'evenodd'}));el('hk-map').querySelector('defs').append(mask);const base=svgNode('path',{d:landData,class:'land-base','fill-rule':'evenodd'});districtLayer.parentNode.insertBefore(base,districtLayer);districtLayer.setAttribute('clip-path','url(#land-mask)');for(const f of geo.features){const node=svgNode('path',{d:pathForGeometry(f.geometry,project),class:'district','data-district':f.properties.District});const title=svgNode('title');title.textContent=f.properties['地區'];node.append(title);districtLayer.append(node)}
    const labels=[['新界',114.11,22.48],['九龙',114.19,22.345],['香港岛',114.18,22.265],['大屿山',113.98,22.245]];for(const [name,lon,lat] of labels){const [x,y]=project([lon,lat]);const t=svgNode('text',{x,y,class:'map-area-label','text-anchor':'middle'});t.textContent=name;el('label-layer').append(t)}
    STATIONS.forEach(s=>{const [x,y]=project([s.lon,s.lat]);s.x=x;s.y=y;const g=svgNode('g',{class:`station-marker ${s.type}`,'data-key':s.key,tabindex:'0',role:'button','aria-label':`${s.zh}${typeText(s.type)}`});const halo=svgNode('circle',{cx:x,cy:y,r:20,class:'marker-halo'});const outcome=svgNode('circle',{cx:x,cy:y,r:16,class:'outcome-ring'});const core=s.type==='roadside'?svgNode('path',{d:`M${x},${y-10} L${x+10},${y} L${x},${y+10} L${x-10},${y} Z`,class:'marker-core'}):svgNode('circle',{cx:x,cy:y,r:8,class:'marker-core'});const status=svgNode('text',{x:x+13,y:y-11,class:'data-status-mark','text-anchor':'middle'});status.textContent='!';const name=svgNode('text',{x:x+12,y:y-12,class:'station-name-label'});name.textContent=s.zh;const title=svgNode('title');title.textContent=`${s.zh} · ${typeText(s.type)}`;g.append(halo,outcome,core,status,name,title);g.addEventListener('click',()=>selectStation(s.key));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectStation(s.key)}});el('marker-layer').append(g)});layoutStationLabels();state.mapReady=true;renderMapState()}
  catch(err){el('district-layer').textContent='';el('map-viewport').append(svgNode('text',{x:500,y:330,fill:'#d7e7dd','text-anchor':'middle'})).textContent='地图数据未能载入，请通过本地服务器打开网页。'}}

function historyRow(s){return state.historyRows.get(s.key)}
function riskFromNumber(v){return v==null?'unknown':v>=11?'serious':v>=8?'very-high':v>=7?'high':v>=4?'moderate':'low'}
function pointRisk(s){if(state.mapMode==='history')return riskFromNumber(historyRow(s)?.observed);const data=state.values.get(s.key);return data&&!isStale(data.publish_date)?riskClass(data.health_risk):'unknown'}
function pointStatus(s){if(state.mapMode==='history')return historyRow(s)?.observed==null?'unavailable':'fresh';const data=state.values.get(s.key);return !data?'unavailable':isStale(data.publish_date)?'stale':'fresh'}
function outcomeOf(row){if(!row?.eligible)return 'ineligible';if(row.ruleAlert)return row.actualHighIn2h?'hit':'false-alert';return row.actualHighIn2h?'missed':'none'}
function outcomeText(row){return ({hit:'命中', 'false-alert':'误报',missed:'漏报',none:'无预警',ineligible:row?.reason||'未纳入评估'})[outcomeOf(row)]}
function renderDataStatusSummary(){const history=state.mapMode==='history',loading=!history&&state.dataMode==='loading',count=loading?null:STATIONS.filter(s=>pointStatus(s)!=='fresh').length;el('data-status-label').textContent=history?'观测缺失提示':'缺失／过期提示';el('data-status-hint').textContent=history?'勾选后以 ! 标记缺少当时读数的测站':'勾选后以 ! 标记缺失或超过 3 小时的测站';el('data-status-count').textContent=count==null?'检查中':`${history?'缺失':'异常'} ${count} 站`;el('data-status-count').classList.toggle('has-issues',count>0)}
function renderMapState(){renderDataStatusSummary();if(!state.mapReady)return;const history=state.mapMode==='history',frame=el('map-frame');frame.classList.toggle('show-station-names',el('station-name-toggle').checked);frame.classList.toggle('show-data-status',el('data-status-toggle').checked);frame.classList.toggle('show-outcomes',history&&el('outcome-toggle').checked);el('legend-outcomes').hidden=!(history&&el('outcome-toggle').checked);el('legend-boundary').hidden=!el('boundary-toggle').checked;document.querySelectorAll('.station-marker').forEach(n=>{const s=STATIONS.find(x=>x.key===n.dataset.key);const match=(state.filter==='all'||s.type===state.filter)&&matches(s),data=state.values.get(s.key),row=historyRow(s);n.dataset.risk=pointRisk(s);n.dataset.status=pointStatus(s);n.dataset.outcome=history?outcomeOf(row):'none';const detail=history?`${state.historyTime?.replace('T',' ')} 历史 AQHI ${row?.observed??'暂无'}，${outcomeText(row)}`:data&&!isStale(data.publish_date)?`${data.aqhi}，${riskText(data.health_risk)}风险`:'数据缺失或过期';n.setAttribute('aria-label',`${s.zh}${typeText(s.type)}，${detail}`);n.classList.toggle('filtered',!match);n.classList.toggle('selected',s.key===state.selected)});document.querySelectorAll('.district').forEach(n=>{n.classList.toggle('no-boundaries',!el('boundary-toggle').checked);n.classList.toggle('selected-district',n.dataset.district===STATIONS.find(s=>s.key===state.selected)?.district)});renderPopup()}
function refreshMapView(){const history=state.mapMode==='history';el('map-mode-current').classList.toggle('active',!history);el('map-mode-history').classList.toggle('active',history);el('map-mode-current').setAttribute('aria-pressed',String(!history));el('map-mode-history').setAttribute('aria-pressed',String(history));el('map-view-kicker').textContent=history?'HISTORICAL REPLAY':'OFFICIAL OBSERVATION';el('map-view-title').textContent=history?'测站历史回放':'全港测站当前观测';el('map-top-note').textContent=history?`${state.historyTime?.replace('T',' · ')||'历史'} 香港时间 · 回测数据，非当前预警`:'行政区界反映地理分区，不代表测站覆盖范围';el('unknown-legend-label').textContent=history?'无有效读数':'缺失/过期';el('map-history-hour').hidden=!history;el('outcome-layer-option').hidden=!history;renderList();renderDetail();renderMapState()}
function setMapMode(mode){if(mode==='history'&&!state.historyReport)return;state.mapMode=mode;state.popupOpen=false;refreshMapView()}
window.setAirHistory=report=>{state.historyReport=report;state.historyTime=report.replay.end;state.historyRows=new Map(report.replay.rows.filter(row=>row.time===state.historyTime).map(row=>[row.station,row]));const select=el('map-history-hour');select.innerHTML=[...new Set(report.replay.rows.map(row=>row.time))].sort().map(time=>`<option value="${time}">${time.replace('T',' · ')} 香港时间</option>`).join('');select.value=state.historyTime;el('map-mode-history').disabled=false};
window.setAirHistoryTime=time=>{if(!state.historyReport)return;state.historyTime=time;state.historyRows=new Map(state.historyReport.replay.rows.filter(row=>row.time===time).map(row=>[row.station,row]));el('map-history-hour').value=time;if(state.mapMode==='history')refreshMapView()};
function matches(s){const q=state.query.trim().toLowerCase();return !q || `${s.zh} ${s.en} ${s.key} ${s.district}`.toLowerCase().includes(q)}
function renderList(){const shown=STATIONS.filter(s=>(state.filter==='all'||s.type===state.filter)&&matches(s));el('list-count').textContent=`${shown.length} 站`;el('station-list').innerHTML=shown.length?shown.map(s=>{const d=state.values.get(s.key),row=historyRow(s),history=state.mapMode==='history',r=history?riskFromNumber(row?.observed):riskClass(d?.health_risk),value=history?(row?.observed==null?'—':row.observed===11?'10+':row.observed):d?.aqhi??'—';return `<button type="button" class="station-row ${s.key===state.selected?'selected':''}" data-key="${esc(s.key)}"><span class="row-symbol ${s.type}"></span><span class="row-copy"><b>${esc(s.zh)}</b><small>${esc(s.en.toUpperCase())} · ${history?'历史':typeText(s.type)}</small></span><span class="row-aqhi ${r}">${esc(value)}</span></button>`}).join(''):'<div class="empty-list">没有匹配的测站。试试其他名称。</div>';el('station-list').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>selectStation(b.dataset.key)))}
function selectStation(key){const s=STATIONS.find(x=>x.key===key);if(!s)return;state.selected=key;state.popupOpen=true;renderList();renderDetail();renderMapState();if(window.innerWidth<760)el('map-frame').scrollIntoView({behavior:'smooth',block:'center'})}
function advice(risk,type){if(!risk)return '当前缺少有效读数。请查看官方发布页后再作决定。';if(risk==='Low')return '当前属于低风险。外出前仍建议留意下一次官方更新。';if(risk==='Moderate')return type==='roadside'?'当前属于中风险。若会长时间停留在繁忙道路附近，可优先留意路边站变化。':'当前属于中风险。一般情况下可照常安排活动，敏感人士应关注自身状况。';return '风险已升高。不同人群的建议不同，请查看香港环保署对应风险级别的官方健康建议。'}
function renderDetail(){const s=STATIONS.find(x=>x.key===state.selected);if(state.mapMode==='history'){const row=historyRow(s),v=row?.observed,shown=v==null?'—':v===11?'10+':v;el('station-detail').innerHTML=`<div class="detail-intro"><h2>${esc(s.zh)}</h2><div class="detail-en">历史回放 · ${typeText(s.type)}</div></div><div class="detail-big"><strong>${shown}</strong><span>AQHI</span></div><span class="risk-badge ${riskFromNumber(v)}">${esc(outcomeText(row))}</span><div class="detail-divider"></div><div class="detail-meta"><div><span>回放时间</span><b>${esc(formatDate(state.historyTime))}</b></div><div><span>评估状态</span><b>${row?.eligible?'已纳入':'未纳入'}</b></div></div><div class="detail-compact-note">历史测试集<br>不代表当前预警</div>`;return}const d=state.values.get(s.key),published=d?.publish_date||state.published,stale=!d||isStale(published),risk=stale?null:d.health_risk;el('station-detail').innerHTML=`<div class="detail-intro"><h2>${esc(s.zh)}</h2><div class="detail-en">${esc(s.en.toUpperCase())}</div><span class="detail-type ${s.type}">${s.type==='roadside'?'◇':'○'} ${typeText(s.type)}</span></div><div class="detail-big"><strong>${esc(d?.aqhi??'—')}</strong><span>AQHI</span></div><span class="risk-badge ${riskClass(risk)}">${stale?'缺失/过期':`${riskText(risk)}风险`}</span><div class="detail-divider"></div><div class="detail-meta"><div><span>所属区</span><b>${esc(districtZh(s.district))}</b></div><div><span>发布时间</span><b>${formatDate(published)}</b></div></div><div class="detail-compact-note">点位约略定位<br>读数仅代表测站</div>`}
function renderPopup(){const popup=el('map-popup'),frame=el('map-frame');if(!state.popupOpen||!state.mapReady){popup.hidden=true;frame.classList.remove('popup-visible');return}const s=STATIONS.find(x=>x.key===state.selected);popup.hidden=false;frame.classList.add('popup-visible');if(state.mapMode==='history'){const row=historyRow(s),v=row?.observed,shown=v==null?'—':v===11?'10+':v;popup.innerHTML=`<button class="popup-close" type="button" aria-label="关闭测站卡片">×</button><div class="popup-kicker">历史回放 · ${esc(formatDate(state.historyTime))}</div><div class="popup-heading"><strong>${esc(s.zh)}</strong><span class="popup-score">${shown} <small>AQHI</small></span></div><div class="popup-meta"><span class="risk-badge ${riskFromNumber(v)}">${esc(outcomeText(row))}</span><span>${typeText(s.type)}</span></div><p>${row?.eligible?(row.actualHighIn2h?`${row.leadHours} 小时后达 7+；${row.ruleAlert?'规则已提醒':'规则未提醒'}。`:'未来两小时未达 7+。'):esc(row?.reason||'未纳入评估。')}</p><small class="popup-foot">历史测试集 · 非当前预警</small>`}else{const d=state.values.get(s.key),published=d?.publish_date||state.published,stale=!d||isStale(published),risk=stale?null:d.health_risk;popup.innerHTML=`<button class="popup-close" type="button" aria-label="关闭测站卡片">×</button><div class="popup-kicker">${typeText(s.type)} · ${esc(districtZh(s.district))}</div><div class="popup-heading"><strong>${esc(s.zh)}</strong><span class="popup-score ${riskClass(risk)}">${esc(d?.aqhi??'—')} <small>AQHI</small></span></div><div class="popup-meta"><span class="risk-badge ${riskClass(risk)}">${stale?'缺失/过期':`${riskText(risk)}风险`}</span><span>${formatDate(published)}</span></div><p>${stale?'数据缺失或超过 3 小时，请核对官方最新发布。':esc(advice(risk,s.type))}</p><small class="popup-foot">单点读数 · 不代表整个行政区</small>`}popup.querySelector('.popup-close').addEventListener('click',()=>{state.popupOpen=false;popup.hidden=true;frame.classList.remove('popup-visible')});requestAnimationFrame(positionPopup)}
function positionPopup(){const popup=el('map-popup');if(popup.hidden)return;const marker=document.querySelector(`.station-marker[data-key="${CSS.escape(state.selected)}"] .marker-core`),frame=el('map-frame');if(!marker)return;const mark=marker.getBoundingClientRect(),area=frame.getBoundingClientRect(),x=mark.left+mark.width/2-area.left,y=mark.top-area.top,half=popup.offsetWidth/2+8,above=y-popup.offsetHeight-14>=8;popup.classList.toggle('below-marker',!above);popup.style.left=`${Math.max(half,Math.min(area.width-half,x))}px`;popup.style.top=`${above?y-12:Math.min(area.height-popup.offsetHeight-8,y+14)}px`}
const districtNames={'North District':'北区','Sha Tin District':'沙田区','Tai Po District':'大埔区','Yuen Long District':'元朗区','Tuen Mun District':'屯门区','Islands District':'离岛区','Tsuen Wan District':'荃湾区','Kwai Tsing District':'葵青区','Sham Shui Po District':'深水埗区','Kwun Tong District':'观塘区','Central and Western District':'中西区','Eastern District':'东区','Southern District':'南区','Sai Kung District':'西贡区','Wan Chai District':'湾仔区','Yau Tsim Mong District':'油尖旺区'};
function districtZh(name){return districtNames[name]||name}
function rangeFor(type){const nums=STATIONS.filter(s=>s.type===type).map(s=>score(state.values.get(s.key)?.aqhi)).filter(Number.isFinite);if(!nums.length)return '—';return `${Math.min(...nums)===11?'10+':Math.min(...nums)}–${Math.max(...nums)===11?'10+':Math.max(...nums)}`}
function renderOverview(){el('available-count').innerHTML=`${state.values.size} <small>/ 18</small>`;el('general-range').textContent=rangeFor('general');el('roadside-range').textContent=rangeFor('roadside');el('data-time').textContent=formatDate(state.published);let label=state.dataMode==='live'?'官方接口已连接':state.dataMode==='snapshot'?'本地存档 · 非实时':'数据暂不可用';if(isStale(state.published)&&state.values.size)label+=' · 数据已超过 3 小时';el('data-status').textContent=label;el('data-status').classList.toggle('warn',state.dataMode!=='live'||isStale(state.published))}
function validAQHI(data){if(!Array.isArray(data))throw new Error('AQHI 格式错误');const known=new Set(STATIONS.map(s=>s.key));const valid=data.filter(x=>known.has(x.station)&&/^(?:[1-9]|10|10\+)$/.test(String(x.aqhi))&&typeof x.publish_date==='string');if(valid.length<15)throw new Error('AQHI 测站不足');return valid}
async function loadAQHI(){let data;try{const response=await fetch(`${API}&_=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error('AQHI 接口失败');data=validAQHI(await response.json());state.dataMode='live'}catch(err){try{const response=await fetch('./data/aqhi-snapshot.json');data=validAQHI(await response.json());state.dataMode='snapshot'}catch(_){state.dataMode='error';data=[]}}state.values=new Map(data.map(x=>[x.station,x]));state.published=data.map(x=>x.publish_date).sort().at(-1)||null;renderOverview();renderList();renderDetail();renderMapState()}
function validForecast(data){if(!Array.isArray(data))throw new Error('预报格式错误');return data.filter(x=>['general','roadside'].includes(x.type)&&/^\d{4}-\d\d-\d\d$/.test(x.date)&&['A.M.','P.M.'].includes(x.time)&&typeof x.health_risk_min==='string'&&typeof x.health_risk_max==='string').slice(0,8)}
async function loadForecast(){try{const response=await fetch(`${FORECAST_API}?_=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error('预报接口失败');state.forecast=validForecast(await response.json());state.forecastMode='live'}catch(err){try{const response=await fetch('./data/forecast-snapshot.json');state.forecast=validForecast(await response.json());state.forecastMode='snapshot'}catch(_){state.forecast=[];state.forecastMode='error'}}renderForecast()}
function renderForecast(){if(!state.forecast.length){el('forecast-grid').innerHTML='<div class="forecast-card">暂时无法读取官方预报。请稍后刷新。</div>';return}const list=state.forecast.slice().sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time)||a.type.localeCompare(b.type));el('forecast-grid').innerHTML=list.map(f=>{const range=f.health_risk_min===f.health_risk_max?riskText(f.health_risk_min):`${riskText(f.health_risk_min)}至${riskText(f.health_risk_max)}`;return `<article class="forecast-card ${esc(f.type)}"><div class="top"><span class="day">${esc(f.date.slice(5).replace('-','月'))}日 · ${f.time==='A.M.'?'上午':'下午'}</span><span class="type">${typeText(f.type)}</span></div><strong>${range}风险</strong><span class="source">${state.forecastMode==='snapshot'?'本地存档 · ':''}官方预报 ${formatDate(f.publish_date)} 发布</span></article>`}).join('')}
function setZoom(next,anchor={x:500,y:340}){const old=state.zoom;state.zoom=Math.max(1,Math.min(3,next));if(state.zoom===old)return;state.panX=anchor.x-(anchor.x-state.panX)*(state.zoom/old);state.panY=anchor.y-(anchor.y-state.panY)*(state.zoom/old);updateTransform()}
function updateTransform(){const capX=(state.zoom-1)*500,capY=(state.zoom-1)*340;state.panX=Math.max(-capX,Math.min(capX,state.panX));state.panY=Math.max(-capY,Math.min(capY,state.panY));el('map-viewport').setAttribute('transform',`translate(${state.panX} ${state.panY}) scale(${state.zoom})`);requestAnimationFrame(positionPopup)}
function keepSelectionVisible(){const current=STATIONS.find(s=>s.key===state.selected);if(current&&(state.filter==='all'||current.type===state.filter)&&matches(current))return;const next=STATIONS.find(s=>(state.filter==='all'||s.type===state.filter)&&matches(s));if(next){state.selected=next.key;renderDetail()}}
function initControls(){el('station-search').addEventListener('input',e=>{state.query=e.target.value;keepSelectionVisible();renderList();renderMapState()});document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{state.filter=btn.dataset.filter;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===btn));keepSelectionVisible();renderList();renderMapState()}));el('boundary-toggle').addEventListener('change',renderMapState);el('zoom-in').addEventListener('click',()=>setZoom(state.zoom+.35));el('zoom-out').addEventListener('click',()=>setZoom(state.zoom-.35));el('reset-map').addEventListener('click',()=>{state.zoom=1;state.panX=0;state.panY=0;updateTransform()});document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();el('station-search').focus()}});const svg=el('hk-map');svg.addEventListener('wheel',e=>{e.preventDefault();const rect=svg.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width*1000,y=(e.clientY-rect.top)/rect.height*680;setZoom(state.zoom+(e.deltaY<0?.22:-.22),{x,y})},{passive:false});let drag=null;svg.addEventListener('pointerdown',e=>{if(state.zoom===1||e.target.closest('.station-marker'))return;drag={x:e.clientX,y:e.clientY,px:state.panX,py:state.panY};svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointermove',e=>{if(!drag)return;const r=svg.getBoundingClientRect();state.panX=drag.px+(e.clientX-drag.x)/r.width*1000;state.panY=drag.py+(e.clientY-drag.y)/r.height*680;updateTransform()});svg.addEventListener('pointerup',()=>drag=null);svg.addEventListener('pointercancel',()=>drag=null)}
window.addEventListener('resize',positionPopup);
function initLayerControls(){const button=el('layer-menu-button'),menu=el('layer-menu');const close=()=>{menu.hidden=true;button.setAttribute('aria-expanded','false')};button.addEventListener('click',()=>{menu.hidden=!menu.hidden;button.setAttribute('aria-expanded',String(!menu.hidden))});document.addEventListener('click',event=>{if(!event.target.closest('.layer-picker'))close()});document.addEventListener('keydown',event=>{if(event.key==='Escape')close()});for(const id of ['station-name-toggle','data-status-toggle','outcome-toggle'])el(id).addEventListener('change',renderMapState);el('map-mode-current').addEventListener('click',()=>setMapMode('current'));el('map-mode-history').addEventListener('click',()=>setMapMode('history'));el('map-history-hour').addEventListener('change',event=>{const other=el('replay-hour');other.value=event.target.value;other.dispatchEvent(new Event('change'))})}
initControls();initLayerControls();renderList();renderDetail();renderForecast();loadMap();loadAQHI();loadForecast();
